# Generated by Django 2.2.5 on 2021-05-08 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=140)),
                ('instant_book', models.BooleanField(default=False)),
                ('working_hours', models.CharField(max_length=140)),
                ('menuname_1', models.CharField(max_length=80)),
                ('menuprice_1', models.IntegerField()),
                ('menuname_2', models.CharField(max_length=80)),
                ('menuprice_2', models.IntegerField()),
                ('menuname_3', models.CharField(max_length=80)),
                ('menuprice_3', models.IntegerField()),
                ('menuname_4', models.CharField(max_length=80)),
                ('menuprice_4', models.IntegerField()),
                ('menuname_5', models.CharField(max_length=80)),
                ('menuprice_5', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
