# Generated by Django 2.2.5 on 2021-05-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210517_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='working_hours',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='working_hours_end',
            field=models.TimeField(null=True),
        ),
    ]
