# Generated by Django 2.2.5 on 2021-05-10 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_auto_20210509_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('visit_time', models.DateField()),
                ('num_of_visitors', models.IntegerField()),
                ('message', models.TextField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancled', 'Cancle'), ('confirmed', 'Confirmed')], default='pending', max_length=12)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
